INSERT INTO users (user_username, user_password, created_at)
VALUES
    ('CodeMaster_42', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW()),
    ('WebWizard89', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW()),
    ('ByteNinja', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW()),
    ('CodeSmith', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW()),
    ('WebSlinger', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW()),
    ('DataGeek', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW()),
    ('CyberGuardian', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW()),
    ('InfoSecGuy', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW()),
    ('FirewallFreak', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW()),
    ('PhishBuster', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW()),
    ('VPNinja', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW()),
    ('MalwareSlayer', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW()),
    ('StartupDreamer', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW()),
    ('CloudSavvy', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW()),
    ('AzureGuru', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW()),
    ('GCPExplorer', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW()),
    ('DigitalNomad', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW()),
    ('IBMCloudWhiz', '$2a$10$ubDrAgAsn.qXiObJF5mNTe2rFl1glDxrNnOYr6aU4EnoyzQ8MyWVK', NOW());