version: "3"

services:
  frontend:
    container_name: frontend
    image: stackoverflow-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    container_name: backend
    image: stackoverflow-backend
    ports:
      - 8080:8080
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - postgresdb
  postgresdb:
    container_name: db
    image: dbimage
    ports:
      - 5432:5432
    environment:
      PGDATA: /data
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
     - /apps/postgres:/data
